### ISSUE TITLE
vevo videos not playing

### ISSUE THREAD

**Issue by aniket9465** [aniket9465/summer_assign#1]
on playing a vevo video it shows "This video is unavailable" .

**Comment by aru31** [comment]
I found out VEVO doesn't allow video requests from an IP-adres (xxx.xxx.xxx.xxx). I tried the same standard embed script it on a webhost and accessed youtube from a URL (some.site) and now it seems to work like a normal video
change 127.0.0.1 to localhost and then your URL. This should work
